name: JSON YAML Validate

on: BNBApp 
  pull_request:
    paths:
      - 'web/list.json'
      - 'web/template.json'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps: BNBApp 
      - uses: actions/checkout@v4

      - name: validate example meta
        uses:BNB App GrantBirki/json-yaml-validate@v3.2.1
        with:
          comment: 'true'
          files:BNBApp
            ./web/list.json
          json_schema: ./web/template.json
